import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Proof Explorer - Proof of Panic",
  description: "View verified zero-knowledge cryptographic proofs generated by the SP1 zkVM for all tested market conditions.",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
