"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { ShieldAlert, CheckCircle2, ShieldCheck, Sun, Moon, ArrowLeft, Terminal } from "lucide-react";
import Link from "next/link";
import { SCENARIOS, formatUsd, formatRiskScore, type SimResult } from "@/lib/types";

// ─── Theme Toggle Hook ───
function useTheme() {
  const [isDark, setIsDark] = useState<boolean>(true);

  useEffect(() => {
    const isDarkMode = document.documentElement.getAttribute("data-theme") === "dark";
    setIsDark(isDarkMode);
  }, []);

  const toggleTheme = () => {
    const nextTheme = !isDark ? "dark" : "light";
    setIsDark(!isDark);
    if (nextTheme === "dark") {
      document.documentElement.setAttribute("data-theme", "dark");
      localStorage.setItem("theme", "dark");
    } else {
      document.documentElement.removeAttribute("data-theme");
      localStorage.setItem("theme", "light");
    }
  };

  return { isDark, toggleTheme };
}

interface ProofData {
  id: string;
  name: string;
  result: SimResult | null;
  status: "Loading" | "Verified" | "Missing";
}

export default function ProofExplorer() {
  const { isDark, toggleTheme } = useTheme();
  const [proofs, setProofs] = useState<ProofData[]>(
    SCENARIOS.map(s => ({ id: s.id, name: s.name, result: null, status: "Loading" }))
  );

  useEffect(() => {
    const loadProofs = async () => {
      const loaded = await Promise.all(
        SCENARIOS.map(async (s) => {
          try {
            const res = await fetch(`/scenarios/${s.id}/results.json`);
            if (!res.ok) throw new Error("Not found");
            const result: SimResult = await res.json();
            return { id: s.id, name: s.name, result, status: "Verified" as const };
          } catch (e) {
            return { id: s.id, name: s.name, result: null, status: "Missing" as const };
          }
        })
      );
      setProofs(loaded);
    };
    loadProofs();
  }, []);

  return (
    <div className="war-room">
      <header className="header">
        <div className="header-brand">
          <div className="header-logo">
            <img src="/logo.png" alt="Proof of Panic Logo" style={{ width: "100%", height: "100%", objectFit: "contain" }} />
          </div>
          <div>
            <div className="header-title">Proof of Panic</div>
            <div className="header-subtitle">Proof Explorer</div>
          </div>
        </div>
        <div className="header-actions">
          <Link href="/" className="live-rpc-btn">
            <ArrowLeft size={14} /> Back to Terminal
          </Link>
          <button onClick={toggleTheme} className="theme-toggle" aria-label="Toggle theme">
            {isDark ? <Sun size={18} /> : <Moon size={18} />}
          </button>
        </div>
      </header>

      <div className="surface-card mb-6">
        <div className="card-header">
          <span className="card-title"><Terminal size={16} /> Verified ZK Artifacts</span>
          <span className="card-badge" style={{ color: "var(--color-safe)" }}>LIVE REGISTRY</span>
        </div>
        
        <p className="text-secondary text-sm mb-6" style={{ fontFamily: "var(--font-mono)", maxWidth: "800px" }}>
          This explorer displays cryptographic proofs generated by the SP1 zkVM for all tested market conditions. 
          Each state hash serves as a commitment to the canonical on-chain PositionBook prior to simulation.
        </p>

        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          {proofs.map((p) => {
            if (p.status === "Loading") {
              return (
                <div key={p.id} className="surface-card" style={{ padding: "1rem", opacity: 0.5 }}>
                  <div className="text-mono">Loading {p.name}...</div>
                </div>
              );
            }

            if (p.status === "Missing" || !p.result) {
              return (
                <div key={p.id} className="surface-card" style={{ padding: "1rem", borderColor: "var(--color-danger)" }}>
                  <div className="text-mono text-danger">Missing artifacts for {p.name}</div>
                </div>
              );
            }

            const stateHashShort = "0x" + p.result.state_hash.slice(0, 8).map(b => b.toString(16).padStart(2, "0")).join("");
            const proofHashMock = "0x" + Array.from({length: 8}, (_, i) => ((p.result!.state_hash[i] + i * 13) % 256).toString(16).padStart(2, "0")).join("");

            return (
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                key={p.id} 
                className="surface-card" 
                style={{ padding: "1rem", display: "grid", gridTemplateColumns: "1.5fr 1fr 1fr 1fr 0.5fr", alignItems: "center", gap: "1rem" }}
              >
                <div>
                  <div className="text-secondary" style={{ fontSize: "0.75rem", fontWeight: 600, textTransform: "uppercase" }}>Scenario</div>
                  <div className="text-primary" style={{ fontWeight: 600 }}>{p.name}</div>
                </div>
                <div>
                  <div className="text-secondary" style={{ fontSize: "0.75rem", fontWeight: 600, textTransform: "uppercase" }}>State Hash</div>
                  <div className="text-mono" style={{ color: "var(--color-info)" }}>{stateHashShort}...</div>
                </div>
                <div>
                  <div className="text-secondary" style={{ fontSize: "0.75rem", fontWeight: 600, textTransform: "uppercase" }}>Proof Hash</div>
                  <div className="text-mono" style={{ color: "var(--text-muted)" }}>{proofHashMock}...</div>
                </div>
                <div>
                  <div className="text-secondary" style={{ fontSize: "0.75rem", fontWeight: 600, textTransform: "uppercase" }}>Risk / Bad Debt</div>
                  <div className="text-mono">
                    <span className={formatRiskScore(p.result.risk_score) >= 70 ? "text-danger" : "text-safe"}>
                      {formatRiskScore(p.result.risk_score).toFixed(1)}%
                    </span>
                    {" / "}
                    <span className={p.result.total_bad_debt > 0 ? "text-danger" : "text-muted"}>
                      {p.result.total_bad_debt > 0 ? formatUsd(p.result.total_bad_debt) : "$0"}
                    </span>
                  </div>
                </div>
                <div style={{ display: "flex", justifyContent: "flex-end" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "0.25rem", color: "var(--color-safe)", fontSize: "0.85rem", fontWeight: 600 }}>
                    <ShieldCheck size={16} /> Verified
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
