use anchor_lang::prelude::*;
use anchor_lang::solana_program::instruction::Instruction;
use anchor_lang::solana_program::program::invoke;
use sha2::{Digest, Sha256};

use crate::constants::*;
use crate::errors::PanicError;
use crate::state::*;

/// Submit a ZK proof of a stress-test simulation and verify it on-chain.
///
/// Flow:
/// 1. Compute SHA-256 of the on-chain PositionBook to anchor the proof
/// 2. CPI to the Sunspot verifier program to verify the Groth16 proof
/// 3. If proof is valid and risk exceeds threshold, activate circuit breaker
///
/// The `test-mock-verify` feature flag skips the CPI for testing without
/// a deployed Sunspot verifier.
pub fn handler(
    ctx: Context<SubmitProofAndVerify>,
    proof_bytes: Vec<u8>,
    public_inputs: Vec<u8>,
    risk_score: u64,
    bad_debt: u64,
    num_liquidated: u64,
    state_hash: [u8; 32],
) -> Result<()> {
    let position_book = ctx.accounts.position_book.load()?;
    let global_state = &mut ctx.accounts.global_state;
    let risk_config = &ctx.accounts.risk_config;

    // ── Step 1: Verify state hash matches on-chain data ──
    let canonical = position_book.canonical_bytes();
    let mut hasher = Sha256::new();
    hasher.update(&canonical);
    let computed_hash: [u8; 32] = hasher.finalize().into();

    require!(
        computed_hash == state_hash,
        PanicError::StateHashMismatch
    );

    msg!("✓ State hash verified: proof corresponds to on-chain positions");

    // ── Step 2: Verify the ZK proof ──
    #[cfg(not(feature = "test-mock-verify"))]
    {
        // CPI to the Sunspot verifier program.
        // The verifier program was generated by `sunspot deploy` and deployed separately.
        // It expects: proof bytes + public witness as instruction data.
        let verifier_program = &ctx.accounts.sunspot_verifier;

        // Build the verification instruction.
        // Sunspot's verifier expects the proof and public inputs concatenated
        // as the instruction data. The exact format is determined by the
        // verifier program generated for this specific circuit.
        let mut verify_data = Vec::with_capacity(proof_bytes.len() + public_inputs.len());
        verify_data.extend_from_slice(&proof_bytes);
        verify_data.extend_from_slice(&public_inputs);

        let verify_ix = Instruction {
            program_id: verifier_program.key(),
            accounts: vec![],
            data: verify_data,
        };

        invoke(&verify_ix, &[])?;

        msg!("✓ ZK proof verified via Sunspot CPI");
    }

    #[cfg(feature = "test-mock-verify")]
    {
        msg!("⚠ Mock verification mode: proof accepted without CPI");
    }

    // ── Step 3: Update protocol state ──
    let clock = Clock::get()?;
    global_state.last_proof_slot = clock.slot;
    global_state.last_state_hash = state_hash;
    global_state.last_risk_score = risk_score;

    msg!("Risk score: {}/{} ({}.{}%)",
        risk_score,
        RISK_SCORE_MAX,
        risk_score * 100 / RISK_SCORE_MAX,
        (risk_score * 10000 / RISK_SCORE_MAX) % 100,
    );
    msg!("Bad debt: ${}", bad_debt / SCALE);
    msg!("Liquidated positions: {}", num_liquidated);

    // ── Step 4: Circuit breaker logic ──
    if risk_score > risk_config.circuit_breaker_threshold {
        global_state.circuit_breaker_active = true;

        // Reduce max leverage by 50%
        let reduced_leverage = global_state
            .max_leverage
            .checked_mul(CB_LEVERAGE_REDUCTION_BPS)
            .ok_or(PanicError::ArithmeticOverflow)?
            / BPS_DENOMINATOR;

        let old_leverage = global_state.max_leverage;
        global_state.max_leverage = reduced_leverage;

        msg!("══════════════════════════════════════════════");
        msg!("⚠️  CIRCUIT BREAKER ACTIVATED");
        msg!("  Risk score {} exceeds threshold {}",
            risk_score, risk_config.circuit_breaker_threshold);
        msg!("  Max leverage reduced: {}x → {}x",
            old_leverage / SCALE,
            reduced_leverage / SCALE);
        msg!("══════════════════════════════════════════════");
    } else {
        msg!("✓ Protocol is within safe parameters — no circuit breaker needed");
    }

    Ok(())
}

#[derive(Accounts)]
pub struct SubmitProofAndVerify<'info> {
    pub authority: Signer<'info>,

    #[account(
        mut,
        seeds = [GLOBAL_STATE_SEED],
        bump = global_state.bump,
        has_one = authority @ PanicError::Unauthorized,
    )]
    pub global_state: Account<'info, GlobalState>,

    #[account(
        seeds = [RISK_CONFIG_SEED],
        bump = risk_config.bump,
    )]
    pub risk_config: Account<'info, RiskConfig>,

    #[account(
        seeds = [POSITION_BOOK_SEED],
        bump,
    )]
    pub position_book: AccountLoader<'info, PositionBook>,

    /// The Sunspot-generated verifier program.
    /// CHECK: This is validated by the CPI call itself — if the program
    /// doesn't verify the proof correctly, the CPI will fail.
    #[cfg(not(feature = "test-mock-verify"))]
    /// CHECK: Validated by CPI
    pub sunspot_verifier: UncheckedAccount<'info>,
}
